import { Girl, Choice, skillPointEvents } from '@/elmwood/elmwood.ts'
import type { SkillName, SkillPlan, SkillPointId } from '@/elmwood/types/skills.ts'
import { skills } from '@/elmwood/skills.ts'

const noImpact: string = 'This choice has no impact.'
const firstKiss: string = 'Your first kiss only matters for the Harem Wars minigame.'

const isPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, thisGirl: string, ...prereqOf: string[]) =>
    Girl.listIncludes(girls, thisGirl) || (includeUnselectedForScenes && Girl.listIncludesAny(girls, ...prereqOf))
const hasPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, ...prereqGirls: string[]) =>
    includeUnselectedForScenes || Girl.listIncludes(girls, ...prereqGirls)
const isChainedPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, thisGirl: string, prereqOf: string[], prereqGirls: string[]) =>
    isPrerequisite(girls, includeUnselectedForScenes, thisGirl, ...prereqOf) && hasPrerequisite(girls, includeUnselectedForScenes, ...prereqGirls)
const hasSkill = (skillName: SkillName, by: SkillPointId, skillPlan: SkillPlan) => skillPointEvents
    .slice(0, skillPointEvents.findIndex(ev => ev.id === by) + 1).some(ev => skillPlan[ev.id]?.includes(skillName))

function addSkills(episode: number, event: SkillPointId): Choice[] {
    return Object.values(skills).map(({ name }) =>
        new Choice(`Select Skill: ${name}`, `${event}-skill-${name.toLowerCase().replace(/ /g, '-').replace(/[^\w-]/g, '')}`, episode).forSkill(name, event)
    )
}

export const choices: Choice[] = [
    // Episode 1 Choices
    new Choice('You have beautiful eyes.', 'intro3', 1, 'Katie love +1'),
    new Choice('Tell her you got an A* (LIE)', 'intro5v', 1, 'Katie love +1'),
    new Choice('Oui', 'frenchlie2', 1),
    new Choice('No', 'frenchdeeplie3', 1),
    new Choice('Paris', 'frenchdeepestlie4', 1, 'Katie love +1'),
    new Choice('Thank You', 'intro6', 1, 'Katie love +1'),
    new Choice('Stand back', 'intro9x', 1),
    // +30 Skill Points
    ...addSkills(1, 'e1'),
    new Choice('I don\'t think so', 'intro14', 1),
    new Choice('I\'m a feminist', 'intro18', 1, 'Katie & Taylor love +1'),
    new Choice('Yes, of course.', 'intro20', 1),
    new Choice('You\'re beautiful.', 'openlyd3', 1, 'Lydia love +1'),
    new Choice('Maybe you should just be in underwear like me', 'openlyd7', 1, 'Lydia love and lust +1'),
    new Choice('You\'re all really gorgeous.', 'cheertalk3', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Finish your drink', 'cheertalk4x', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Hold her ass', 'cheertalk5o2', 1, 'Lydia lust +1'),
    new Choice('You\'re incredible', 'cheertalk5x', 1, 'Lydia love +1'),
    new Choice('You\'re amazing', 'cheertalk6x', 1, 'Chelsea love +1'),
    new Choice('You were all great', 'cheertalk7all', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('No', 'cheertalk8n', 1),
    new Choice('I don\'t want to have my first kiss now.', 'cheerkiss0', 1, girls => Girl.listIncludesNone(girls, 'Chelsea', 'Lydia', 'Ella')),
    new Choice('Kiss Lydia', 'cheerkisslyd', 1, firstKiss),
    new Choice('Kiss Chelsea', 'cheerkissch', 1, firstKiss),
    new Choice('Kiss Ella', 'cheerkissel', 1, firstKiss),
    new Choice('Grab her ass', 'cheerkisse2', 1, 'Ella lust +1'),
    new Choice('You\'re beautiful', 'paris3', 1, 'Paris love +1'),
    new Choice('Joke about being a fashion model', 'paris7', 1),
    new Choice('Roast her outfit in a joking way', 'paris7y', 1, 'Paris love +1'),
    new Choice('Fashion, duh (JOKE)', 'paris9y', 1, 'Paris love +1'),
    new Choice('Yawn (JOKE)', 'paris9x2', 1, 'Paris love +1'),
    new Choice('Ask her more about her degree', 'paris13', 1),
    new Choice('Tell me about the emu war', 'paris13x', 1, 'Paris love +1'),
    new Choice('Tell me about the pastry war', 'paris13y', 1, 'Paris love +1'),
    new Choice('An emu', 'paris17', 1),
    new Choice('(Flirt)', 'e1paprize', 1),
    new Choice('A kiss', 'e1pakiss', 1, 'Paris love and lust +1'),
    new Choice('You two look cute together', 'joey1y', 1),
    new Choice('How did you two meet?', 'e1joeystory', 1, noImpact),
    new Choice('How do you know Taylor/Katie?', 'e1joeytaykt', 1, noImpact),
    new Choice('What does your t shirt say?', 'e1joeyshirt', 1, noImpact),
    new Choice('(Continue)', 'e1joeycontinue', 1),
    new Choice('I will always get consent', 'e1joey4', 1),
    new Choice('I\'d like to be friends.', 'joey5', 1, 'Chloe & Jordan love +2'),
    new Choice('Yes', 'chelbj4', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella', 'Lydia')),
    new Choice('Warn Her', 'e1chbjcum', 1),
    new Choice('Go with Lydia to the bathroom.', 'lydbj3', 1, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea'])),
    new Choice('Warn Her', 'e1lybjcum', 1, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea')),
    new Choice('There\'s no need to thank me', 'vimeet1', 1, 'Violet love +1'),
    new Choice('Yes', 'e1elbj1', 1, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Ella', ['Lydia'], ['Chelsea', 'Lydia'])),
    new Choice('Warn her', 'e1elbjcum', 1, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Lydia')),
    new Choice('I\'d like that', 'preselinaintrox', 1),
    new Choice('Compliment her', 'preselinaintrox1', 1, 'Katie love +5'),
    new Choice('Compliment Violet', 'preselinaintrox3', 1, 'Violet love +1', girls => Girl.listIncludesNone(girls, 'Taylor')),
    new Choice('Joke about dating all three', 'preselinaintrox4', 1, 'Katie, Taylor, Violet love +1'),
    new Choice('Compliment her and introduce yourself', 'selinaintro3', 1, 'Selina lust +1'),
    new Choice('Let them talk alone (Taylor\'s request)', 'selinaintro5a', 1, 'Taylor love +1, Selina love -1', girls => Girl.listIncludesNone(girls, 'Selina')),
    new Choice('Stay with them (Selina\'s request)', 'selinaintro5b', 1),
    new Choice('I want Selina to stay', 'selinaintro6', 1, 'Selina lust +1'),
    new Choice('(Kiss her)', 'selinaintrokiss', 1, 'Selina lust +1'),
    new Choice('Let\'s go somewhere private', 'selinaintro12', 1),
    new Choice('Yes', 'selinaintro12c', 1),
    new Choice('I\'ll see you there', 'e1ssex1', 1),
    new Choice('Press Violet on why she won\'t', 'hottub1w', 1),
    new Choice('Compliment her', 'hottub1y', 1, 'Violet love +2'),
    new Choice('Enter naked', 'hotnaked1', 1, 'Lydia, Chelsea, Paris, Katie, Taylor, Ella lust +1'),
    new Choice('No more questions', 'hottub2e', 1, 'Just don\'t ask if there are any men at Elmwood.'),
    new Choice('Put your arm around Lydia', 'hottub2e1', 1, 'Lydia lust +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('Continue', 'hottubz2', 1, 'Faster/Slower is okay', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('I don\'t mind', 'hottubz4', 1, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('Ask Lydia a cheeky question', 'e1lyjoke', 1, 'Lydia love +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('I think they sound fun', 'e1endhot2', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Incredible', 'e1nearend1', 1, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('I\'ll be there', 'e1taydebrief1', 1),
    new Choice('Say goodnight to Paris', 'e1pabye', 1),
    new Choice('Ask to take her home', 'e1pabye1', 1, 'Paris love and lust +1'),
    new Choice('Say goodnight to Katie', 'e1ktbye', 1),
    new Choice('Yes', 'e1ktbye2', 1, 'Katie love +1'),
    new Choice('Say goodnight to Chelsea', 'e1chbye', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('Then take me to bed', 'e1chbye1', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('I wish we had some time alone', 'e1chbye1a', 1, (girls, { includeUnselectedForScenes }) => Girl.listIncludes(girls, 'Lydia') && isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('Walk home with Chelsea', 'e1leaveparty3', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella')),
    new Choice('Compliment her', 'e1chsex2', 1, 'Chelsea love +1'),
    new Choice('Eat her pussy', 'e1chforeplay2', 1, 'Chelsea love +1'),
    // Episode 2 Choices
    new Choice('Shake her hand', 'e2sameet5x', 2, 'Saki love +1'),
    new Choice('Sure', 'e2wakeup2y', 2, 'Saki love +1'),
    new Choice('It\'s hot and exhilarating', 'ie2sameet11a', 2, 'Saki lust +1'),
    new Choice('It\'s sweet and beautiful', 'ie2sameet11b', 2, 'Saki lust +1'),
    new Choice('What videos do you make on TitsCock?', 'twinsmeet1', 2),
    new Choice('(Flirt)', 'twinsmeet1y', 2, 'Twins love and lust +1'),
    new Choice('Have you met the other flatmates?', 'twinsmeet4', 2),
    new Choice('She\'s beautiful', 'twinsmeet4a', 2, 'Saki love +1'),
    new Choice('I\'m more interested in you two', 'twinsmeet8d', 2, 'Twins love +1', girls => Girl.listIncludes(girls, 'Chelsea')),
    new Choice('(Reply)', 'e2lytext', 2, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea', 'Ella'])),
    new Choice('I\'ll be there', 'e2lytext2', 2, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea', 'Ella'])),
    new Choice('Sure', 'e2tashleyyoga', 2),
    new Choice('Absolutely', 'e2tashleyyoga2', 2, 'Twins lust +1'),
    new Choice('Cow', 'e2tashleyyoga2a', 2, 'Twins love +1'),
    new Choice('You\'re beautiful', 'e2twinyogacomp1', 2),
    new Choice('You\'re beautiful', 'e2twinyogacomp2', 2, 'Twins love and lust +1'),
    new Choice('(Kiss her)', 'e2lysex3', 2, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea', 'Ella'])),
    new Choice('Fuck Lydia', 'e2lysex4', 2, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea', 'Ella'])),
    new Choice('Squirting is hot!', 'e2lysexsquirt', 2, 'Required for an E4 scene', (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea', 'Ella'])),
    new Choice('Encourage Ella to watch', 'e2lysexwatch', 2, 'Ella lust +5, required for later scene', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia')),
    new Choice('Talk to Ella', 'e2eltalk1', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Try to make her jealous', 'e2eltalk3c', 2, 'Ella lust +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Make her even more jealous', 'e2eltalk4a', 2, 'Ella love +2, lust +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Ask her out on a date', 'e2eltalk5b', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Ask Paris out on a date', 'e2patext1', 2),
    new Choice('Flirt', 'e2patext1a', 2),
    new Choice('Thanks, Tasha', 'e2td1', 2, 'Twins love +1'),
    new Choice('Truth', 'e2tdtruth1', 2, 'Saki & Molly love +1', girls => Girl.listIncludesAny(girls, 'Saki', 'Molly') && Girl.listIncludes(girls, 'Lydia')),
    new Choice('Dare', 'e2ashneck', 2),
    new Choice('Longer, sensual kiss', 'e2ashnecklong', 2, 'Twins love and lust +1 (Requires dare)'),
    new Choice('Sure', 'e2tdsakissplayer', 2, 'Saki love +2'),
    new Choice('Truth', 'e2truth2', 2),
    // new Choice('Dare', 'e2ashspank', 2), // TODO: Uncomment later if flustering Molly is important
    new Choice('Yes (don\'t specify)', 'e2truth2a', 2, 'Saki, Molly, Twins love +1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Saki', 'e2truth2b', 2, 'Saki love +5, Molly, Twins love -1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Molly', 'e2truth2c', 2, 'Molly love +5, Saki, Twins love -1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Tasha & Ashley', 'e2truth2d', 2, 'Twins love +2, Saki, Molly love -2.'),
    new Choice('I dare you to flash your boobs.', 'e2tdround5', 2),
    new Choice('Turn around', 'e2tdturn', 2),
    new Choice('Dare', 'e2tdshowdickoption', 2, 'Saki love +1'),
    new Choice('Show your dick', 'e2tdshowdickoption2', 2, 'Saki, Molly, Twins lust +1'),
    new Choice('Make out with Tasha', 'e2tdround7', 2, 'Twins love +1'),
    new Choice('Defend her', 'e2tdround8', 2),
    new Choice('Sure', 'e2twinhj2', 2),
    new Choice('You can do it', 'e2twinhj4', 2),
    new Choice('You can make me even harder', 'e2twinhj7', 2),
    new Choice('(Kiss her)', 'e2sanight2', 2, 'Saki love +2'),
    new Choice('Buy Molly a vibrator', 'e2ordervibrator1', 2),
    new Choice('Buy DupliDick Vibe', 'e2ordervibrator2', 2),
    new Choice('Introduce yourself', 'e2ntalkx1', 2),
    new Choice('I\'m excited', 'e2ntalkx1b', 2, 'Naomi love +1', (_, __, { skillPlan }) => !hasSkill('Scholar', 'e1', skillPlan)),
    new Choice('I love her research', 'e2ntalkx1scholar', 2, 'Naomi love +2', (_, __, { skillPlan }) => hasSkill('Scholar', 'e1', skillPlan)),
    new Choice('She\'s fantastic', 'e2ntalk2', 2, 'Naomi love +1'),
    new Choice('Highest mark in exam', 'e2nex', 2, 'Naomi love +1'),
    new Choice('Tell two truths, one lie', 'e22tl', 2, 'Naomi love +1'),
    // +20 Skill Points
    ...addSkills(2, 'e2a'),
    new Choice('Have lunch with Naomi', 'e2flecfinal', 2),
    new Choice('Talk to Dr. Riley', 'e2flotalk', 2),
    new Choice('Move seats', 'e2vlecture1', 2, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Nina', 'Dr. Riley', 'Dr. Novotná')),
    new Choice('Answer', 'e2panswer1a', 2, 'Naomi, Dr. Novotná love +1', (_, __, { skillPlan }) => hasSkill('Scholar', 'e2a', skillPlan)),
    new Choice('Stay Quiet', 'e2panswer1b', 2, (_, __, { skillPlan }) => !hasSkill('Scholar', 'e2a', skillPlan)),
    // +10 Skill Points
    ...addSkills(2, 'e2b'),
    new Choice('Talk to Dr. Novotná first', 'e2vertalk', 2),
    new Choice('I\'m interested', 'e2ninatalk2', 2),
    new Choice('Show me the lake & lighthouse', 'e2viextended', 2),
    new Choice('How have you been?', 'e2vilakechat', 2),
    new Choice('I want to be more than friends', 'e2vilove', 2, 'Violet love +5'),
    new Choice('I love Elmwood.', 'e2lighthouse1', 2, 'Violet love +1'),
    new Choice('Compliment her', 'e2eldate0', 2, 'Ella love +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Ask about cheerleading', 'e2eldatemenu1', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Ask about her gymnastics', 'e2eldatemenu2', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('That\'s so impressive!', 'e2eldategym', 2, 'Ella love +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Ask about her friends', 'e2eldatemenu3', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Seduce her', 'e2eldateflirt', 2, (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('You were better', 'e2elaftersex1', 2, 'Ella love +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Lydia', 'Chelsea')),
    new Choice('Meet Nina', 'e2infiltration0', 2),
    new Choice('Let\'s do this. (CONTINUE)', 'e2infiltration1', 2),
    new Choice('(Scan keycard)', 'e2infiltration2', 2),
    new Choice('Straight - through Dr. Novotná\'s lecture room', 'e2infiltration3', 2),
    new Choice('Good idea.', 'e2infiltration4', 2, 'Nina love +1'),
    new Choice('Let\'s take photos', 'e2infiltration5', 2),
    new Choice('Flirt', 'e2infiltration6', 2),
    new Choice('(Fuck her)', 'e2nisex', 2),
    // Episode 3
    new Choice('He pioneered structuralism', 'e3flec1', 3, 'Naomi love +2', (_, __, { skillPlan }) => hasSkill('Scholar', 'e2b', skillPlan)),
    new Choice('He\'s dead', 'e3flec3', 3, (_, __, { skillPlan }) => !hasSkill('Scholar', 'e2b', skillPlan)),
    // +20 Skill Points
    ...addSkills(3, 'e3a'),
    new Choice('We should study together', 'e3essay2', 3),
    new Choice('(Reply)', 'e3chtext1', 3),
    new Choice('Small talk', 'e3chtext2', 3, 'Chelsea love +1'),
    new Choice('Ask on date', 'e3chtext3', 3),
    new Choice('Say hello', 'e3ctalk', 3, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chloe', 'Jordan')),
    new Choice('Ask her what she means', 'e3ctalk2', 3, 'Chloe love +1', (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chloe', 'Jordan')),
    new Choice('Offer to give her some advice', 'e3ctalk7', 3, 'Chloe love +1', (girls, { includeUnselectedForScenes }, { skillPlan }) => hasSkill('Dexterity', 'e3a', skillPlan) && isPrerequisite(girls, includeUnselectedForScenes, 'Chloe', 'Jordan')),
    new Choice('I\'ll be there', 'e3femsocattend', 3, 'Taylor, Katie love +2', (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Taylor', 'Katie')),
    new Choice('All of them', 'e3vlec9', 3, 'Naomi love +1', (_, __, { skillPlan }) => hasSkill('Scholar', 'e3a', skillPlan)),
    // +20 Skill Points
    ...addSkills(3, 'e3b'),
    new Choice('Visit Dr. Riley', 'e3ftalk', 3),
    new Choice('Ask an intelligent question', 'e3floessayq0', 3, (_, __, { skillPlan }) => hasSkill('Deception', 'e3b', skillPlan)),
    new Choice('Ask a question about the essay', 'e3floessayq1', 3),
    new Choice('Ask another question about the essay', 'e3floessayq2', 3),
    new Choice('Make small talk', 'e3flost', 3),
    new Choice('Compliment her teaching', 'e3flostx', 3),
    new Choice('She\'s ok, you\'re better', 'e3flostx2', 3, 'Dr. Riley love +1'),
    new Choice('Compliment her office', 'e3floof', 3),
    new Choice('Flirt', 'e3flofli', 3),
    new Choice('Ask about him', 'e3flofli1', 3),
    new Choice('Flirt', 'e3flofli3', 3, 'Dr. Riley love +1, lust +2', (_, __, { skillPlan }) => hasSkill('MILF Enthusiast', 'e3b', skillPlan)),
    new Choice('Flirt', 'e3flofli3a', 3, 'Dr. Riley love +1, lust +2', (_, __, { skillPlan }) => hasSkill('MILF Enjoyer', 'e3b', skillPlan)),
    new Choice('It was thought provoking', 'e3femsoc2c', 3, 'Taylor, Katie love +1', (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Taylor', 'Katie')),
    new Choice('You look so beautiful', 'e3kttalk1x', 3, 'Katie love +1', (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Katie', ['Taylor'], ['Taylor'])),
    new Choice('Flirt', 'e3kttalk2b', 3, 'Katie love and lust +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Taylor')),
    new Choice('Text me when you\'re home safe', 'e3kttalk4b', 3, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Katie', ['Taylor'], ['Taylor'])),
    new Choice('Kiss/Hug her', 'e3ktkisshug', 3, 'Katie love +1', (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Katie', ['Taylor'], ['Taylor'])),
    new Choice('(Offer your jacket)', 'e3jacket', 3, 'Taylor love +5, Katie love +1', (girls, { includeUnselectedForScenes }) => hasPrerequisite(girls, includeUnselectedForScenes, 'Katie')),
    new Choice('Gestalt School', 'e3nstudy1a', 3, 'Naomi love +1', (_, __, { skillPlan }) => hasSkill('Scholar', 'e3b', skillPlan)),
    new Choice('(Serious)', 'e3nstudy1b', 3, (_, __, { skillPlan }) => !hasSkill('Scholar', 'e3b', skillPlan)),
    new Choice('Help her more', 'e3nstudy2', 3, 'Naomi love +1', (_, __, { skillPlan }) => hasSkill('Persuasion', 'e3b', skillPlan)),
    new Choice('This one\'s great', 'e3nstudy2c', 3, 'Naomi love +2', (_, __, { skillPlan }) => hasSkill('Deception', 'e3b', skillPlan)),
    new Choice('This one\'s ok', 'e3nstudy2b', 3, 'Naomi love +1', (_, __, { skillPlan }) => hasSkill('Scholar', 'e3b', skillPlan) && !hasSkill('Deception', 'e3b', skillPlan)),
    new Choice('(Reassure her & flirt)', 'e3nstudy5c', 3, 'Naomi love +1'),
    new Choice('We\'ll get through it.', 'e3nstudy7b', 3, 'Naomi love +1'),
    new Choice('Kiss her', 'e3nkiss', 3), // Has love requirement. Should be guaranteed if on path
    new Choice('No', 'e3nkissx', 3, 'Naomi love +1'),
    new Choice('Message Selina', 'e3stext', 3),
    new Choice('I don\'t want a date', 'e3stext1', 3),
    new Choice('That\'s not me', 'e3stalk', 3),
    new Choice('Casual sex', 'e3stalk2c', 3),
    new Choice('I promise', 'e3stalk3', 3),
    new Choice('(Flirt)', 'e3stalk4a', 3),
    new Choice('Fuck even harder', 'e3stalk5', 3, 'Selina lust +1'),
    new Choice('Fuck her', 'e3ssex', 3),
    new Choice('Organise date', 'e3patextdate1', 3),
    new Choice('Flirt', 'e3saki3c', 3, 'Saki love +1'),
    new Choice('Kiss her', 'e3saki4', 3),
    new Choice('What\'s the banana for?', 'e3sakibanana', 3),
    new Choice('I can teach you', 'e3sakibanana1', 3),
    new Choice('You did amazing', 'e3sakibanana1a', 3, 'Saki love +1'),
    new Choice('Corrupt', 'e3sakicorruption', 3, 'Saki love +2', (_, __, { skillPlan }) => hasSkill('Corruption', 'e3b', skillPlan)),
    new Choice('Yes', 'e3gym1', 3),
    new Choice('Looks hot', 'e3gym2', 3, 'Twins love and lust +1'),
    new Choice('Easily', 'e3gym3', 3, 'Twins love +1', (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('100kg', 'e3gym3b', 3, 'Twins love +1', (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan) && !hasSkill('Warrior', 'e3b', skillPlan)),
    new Choice('160kg', 'e3gym3c', 3, 'Twins love +2', (_, __, { skillPlan }) => hasSkill('Warrior', 'e3b', skillPlan)),
    new Choice('Flirt', 'e3gym5', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Flirt', 'e3gym6', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Sure', 'e3gym7', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Flirt', 'e3gym10', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Hold', 'e3gym11', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('HOLD!', 'e3gym12', 3, 'Twins love +1', (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('HOOOLDDDD!', 'e3gym13', 3, (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('HOOOOOOOOOOLDDDD!', 'e3gym14', 3, (_, __, { skillPlan }) => hasSkill('Warrior', 'e3b', skillPlan)),
    new Choice('HOOOOOOOOOOLDDDD!', 'e3gym15', 3, 'Twins love +2', (_, __, { skillPlan }) => hasSkill('Warrior', 'e3b', skillPlan)),
    new Choice('Seeing a friend (lie about date)', 'e3massage1a', 3, (girls, _, { skillPlan }) => Girl.listIncludes(girls, 'Paris') && hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Nothing (lie about Paris)', 'e3massage1b', 3, (girls, _, { skillPlan }) => Girl.listIncludes(girls, 'Paris') && !hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Not much, seeing a friend', 'e3massage1c', 3, girls => Girl.listIncludesNone(girls, 'Paris')),
    new Choice('Nothing much', 'e3massage1d', 3, girls => Girl.listIncludesNone(girls, 'Paris')),
    new Choice('Flirt with both', 'e3massage2c', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Try to kiss them', 'e3tashleykiss', 3, 'Twins love +1', (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Offer to massage them', 'e3massage3', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Massage their asses', 'e3massage4', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Massage their pussies', 'e3massage5', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Take off their panties', 'e3massage6', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Make them both cum', 'e3massagedx', 3, (girls, _, { skillPlan }) => ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)) && hasSkill('Oral Mastery', 'e3b', skillPlan)),
    new Choice('Compliment her', 'e3padate1a', 3, 'Paris love +1'),
    new Choice('Roast her outfit', 'e3padate1c', 3, 'Paris love +1'),
    new Choice('Give Paris a striptease', 'e3padate3', 3, 'Paris love +1'),
    new Choice('Tease her', 'e3padate4b', 3, 'Paris love +1'),
    new Choice('Kiss her', 'e3padate6a', 3, 'Paris love +2'),
    new Choice('Come back to mine?', 'e3padate8', 3),
    new Choice('She\'s just a friend', 'e3confront2', 3, (girls, _, { skillPlan }) => Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Here\'s your water', 'e3padate10', 3),
    new Choice('Kiss Paris', 'e3padate10a', 3),
    new Choice('Go further', 'e3padate12', 3),
    new Choice('Confirm plans', 'e3satwake3', 3),
    new Choice('Compliment Chelsea', 'e3ddate5', 3, 'Chelsea love +1'),
    new Choice('You should stay', 'e3ddate7', 3, (_, { includeSideGirls }) => includeSideGirls),
    new Choice('You should go', 'e3ddatekatleaves', 3, 'Chelsea love -2', (_, { includeSideGirls }) => !includeSideGirls),
    new Choice('COCKS OUT, LADS!', 'e3ddate8', 3, 'Chelsea love +2, Kat lust +1', (_, { includeSideGirls }) => includeSideGirls),
    new Choice('Make out with Chelsea', 'e3ddate9', 3, 'Chelsea love +1', (_, { includeSideGirls }) => includeSideGirls),
    new Choice('Flirty', 'e3ddate10a', 3, 'Kat lust +1', (_, { includeSideGirls }) => includeSideGirls),
    new Choice('Flirty', 'e3ddate11a', 3, 'Kat lust +1', (_, { includeSideGirls }) => includeSideGirls),
    new Choice('A kiss', 'e3ddate90', 3, (_, { includeSideGirls }) => includeSideGirls),
    new Choice('Help Chelsea seduce Kat', 'e3ddate110', 3, (_, { includeSideGirls }) => includeSideGirls),
]

export const selectChoice = (id: string): Choice => {
    const choice = choices.find(c => c.optionId === id)
    if (!choice) {
        throw new Error(`Choice ${id} does not exist`)
    }
    return choice
}

export const conflictingChoices: Choice[][] = [
    ['cheerkiss0', 'cheerkisslyd', 'cheerkissch', 'cheerkissel'].map(id => selectChoice(id)),
    ['preselinaintrox1', 'preselinaintrox3', 'preselinaintrox4'].map(id => selectChoice(id)),
    ['ie2sameet11a', 'ie2sameet11b'].map(id => selectChoice(id)),
    ['e2tdtruth1', 'e2ashneck'].map(id => selectChoice(id)),
    // ['e2truth2', 'e2ashspank'].map(id => selectChoice(id)),
    ['e2truth2a', 'e2truth2b', 'e2truth2c', 'e2truth2d'].map(id => selectChoice(id)),
    ['e2ntalkx1b', 'e2ntalkx1scholar'].map(id => selectChoice(id)),
    ['e3massage1a', 'e3massage1b', 'e3massage1c', 'e3massage1d'].map(id => selectChoice(id)),
    ['e3padate1a', 'e3padate1c'].map(id => selectChoice(id)),
]
