import { Girl, Choice, skillPointEvents } from '@/elmwood/elmwood.ts'
import type { SkillName, SkillPlan, SkillPointId } from '@/elmwood/types/skills.ts'
import { skills } from '@/elmwood/skills.ts'
import { type GirlName } from '@/elmwood/types/girls.ts'
import type { ShowChoice } from '@/elmwood/types/choices.ts'

const noImpact: string = 'This choice has no impact.'
const firstKiss: string = 'Your first kiss only matters for the Harem Wars minigame.'

const isPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, thisGirl: GirlName, ...prereqOf: GirlName[]) =>
    Girl.listIncludes(girls, thisGirl) || (includeUnselectedForScenes && Girl.listIncludesAny(girls, ...prereqOf))
const hasPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, ...prereqGirls: GirlName[]) =>
    includeUnselectedForScenes || Girl.listIncludes(girls, ...prereqGirls)
const isChainedPrerequisite = (girls: Girl[], includeUnselectedForScenes: boolean, thisGirl: GirlName, prereqOf: GirlName[], prereqGirls: GirlName[]) =>
    isPrerequisite(girls, includeUnselectedForScenes, thisGirl, ...prereqOf) && hasPrerequisite(girls, includeUnselectedForScenes, ...prereqGirls)
const hasSkill = (skillName: SkillName, by: SkillPointId, skillPlan: SkillPlan) => skillPointEvents
    .slice(0, skillPointEvents.findIndex(ev => ev.id === by) + 1).some(ev => skillPlan[ev.id]?.includes(skillName))
const hasChoices = (shownChoices: Choice[], ...ids: string[]): boolean =>
    ids.every(id => shownChoices.map(ch => ch.optionId).includes(id))
const hasChoicesOr = (shownChoices: Choice[], ...ids: string[]) =>
    ids.some(id => shownChoices.map(ch => ch.optionId).includes(id))

const req = {
    skill: (skillName: SkillName, by: SkillPointId): ShowChoice => (_, __, { skillPlan }) => hasSkill(skillName, by, skillPlan),
    noSkill: (skillName: SkillName, by: SkillPointId): ShowChoice => (_, __, { skillPlan }) => !hasSkill(skillName, by, skillPlan),
    choices: (...ids: string[]): ShowChoice => (_, __, { shownChoices }) => hasChoices(shownChoices, ...ids),
    choicesOr: (...ids: string[]): ShowChoice => (_, __, { shownChoices }) => hasChoicesOr(shownChoices, ...ids),
    noChoices: (...ids: string[]): ShowChoice => (_, __, { shownChoices }) => !hasChoicesOr(shownChoices, ...ids),
    skillAndChoices: (skillName: SkillName, by: SkillPointId, ...ids: string[]): ShowChoice => (_, __, { shownChoices, skillPlan }) => hasChoices(shownChoices, ...ids) && hasSkill(skillName, by, skillPlan),
}

function addSkills(episode: number, event: SkillPointId): Choice[] {
    return Object.values(skills).map(({ name }) =>
        new Choice(`Select Skill: ${name}`, `${event}-skill-${name.toLowerCase().replace(/ /g, '-').replace(/[^\w-]/g, '')}`, episode).forSkill(name, event)
    )
}

export const choices: Choice[] = [
    // Episode 1 Choices
    new Choice('You have beautiful eyes.', 'intro3', 1, 'Katie love +1'),
    new Choice('Tell her you got an A* (LIE)', 'intro5v', 1, 'Katie love +1'),
    new Choice('Oui', 'frenchlie2', 1),
    new Choice('No', 'frenchdeeplie3', 1),
    new Choice('Paris', 'frenchdeepestlie4', 1, 'Katie love +1'),
    new Choice('Thank You', 'intro6', 1, 'Katie love +1'),
    new Choice('Stand back', 'intro9x', 1),
    // +30 Skill Points
    ...addSkills(1, 'e1'),
    new Choice('I don\'t think so', 'intro14', 1),
    new Choice('I\'m a feminist', 'intro18', 1, 'Katie & Taylor love +1'),
    new Choice('Yes, of course.', 'intro20', 1),
    new Choice('You\'re beautiful.', 'openlyd3', 1, 'Lydia love +1'),
    new Choice('Maybe you should just be in underwear like me', 'openlyd7', 1, 'Lydia love and lust +1'),
    new Choice('You\'re all really gorgeous.', 'cheertalk3', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Finish your drink', 'cheertalk4x', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Hold her ass', 'cheertalk5o2', 1, 'Lydia lust +1'),
    new Choice('You\'re incredible', 'cheertalk5x', 1, 'Lydia love +1'),
    new Choice('You\'re amazing', 'cheertalk6x', 1, 'Chelsea love +1'),
    new Choice('You were all great', 'cheertalk7all', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('No', 'cheertalk8n', 1),
    new Choice('I don\'t want to have my first kiss now.', 'cheerkiss0', 1, girls => Girl.listIncludesNone(girls, 'Chelsea', 'Lydia', 'Ella')),
    new Choice('Kiss Lydia', 'cheerkisslyd', 1, firstKiss),
    new Choice('Kiss Chelsea', 'cheerkissch', 1, firstKiss),
    new Choice('Kiss Ella', 'cheerkissel', 1, firstKiss),
    new Choice('Grab her ass', 'cheerkisse2', 1, 'Ella lust +1'),
    new Choice('You\'re beautiful', 'paris3', 1, 'Paris love +1'),
    new Choice('Joke about being a fashion model', 'paris7', 1),
    new Choice('Roast her outfit in a joking way', 'paris7y', 1, 'Paris love +1'),
    new Choice('Fashion, duh (JOKE)', 'paris9y', 1, 'Paris love +1'),
    new Choice('Yawn (JOKE)', 'paris9x2', 1, 'Paris love +1'),
    new Choice('Ask her more about her degree', 'paris13', 1),
    new Choice('Tell me about the emu war', 'paris13x', 1, 'Paris love +1'),
    new Choice('Tell me about the pastry war', 'paris13y', 1, 'Paris love +1'),
    new Choice('An emu', 'paris17', 1),
    new Choice('(Flirt)', 'e1paprize', 1),
    new Choice('A kiss', 'e1pakiss', 1, 'Paris love and lust +1'),
    new Choice('You two look cute together', 'joey1y', 1),
    new Choice('How did you two meet?', 'e1joeystory', 1, noImpact),
    new Choice('How do you know Taylor/Katie?', 'e1joeytaykt', 1, noImpact),
    new Choice('What does your t shirt say?', 'e1joeyshirt', 1, noImpact),
    new Choice('(Continue)', 'e1joeycontinue', 1),
    new Choice('I will always get consent', 'e1joey4', 1),
    new Choice('I\'d like to be friends.', 'joey5', 1, 'Chloe & Jordan love +2'),
    new Choice('Yes', 'chelbj4', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella', 'Lydia')),
    new Choice('Warn Her', 'e1chbjcum', 1),
    new Choice('Go with Lydia to the bathroom.', 'lydbj3', 1, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Lydia', ['Ella'], ['Chelsea'])),
    new Choice('Warn Her', 'e1lybjcum', 1, req.choices('lydbj3')),
    new Choice('There\'s no need to thank me', 'vimeet1', 1, 'Violet love +1'),
    new Choice('Yes', 'e1elbj1', 1, (girls, { includeUnselectedForScenes }) => isChainedPrerequisite(girls, includeUnselectedForScenes, 'Ella', ['Lydia'], ['Chelsea', 'Lydia'])),
    new Choice('Warn her', 'e1elbjcum', 1, req.choices('e1elbj1')),
    new Choice('I\'d like that', 'preselinaintrox', 1),
    new Choice('Compliment her', 'preselinaintrox1', 1, 'Katie love +5'),
    new Choice('Compliment Violet', 'preselinaintrox3', 1, 'Violet love +1', girls => Girl.listIncludesNone(girls, 'Taylor')),
    new Choice('Joke about dating all three', 'preselinaintrox4', 1, 'Katie, Taylor, Violet love +1'),
    new Choice('Compliment her and introduce yourself', 'selinaintro3', 1, 'Selina lust +1'),
    new Choice('Let them talk alone (Taylor\'s request)', 'selinaintro5a', 1, 'Taylor love +1, Selina love -1', girls => Girl.listIncludesNone(girls, 'Selina')),
    new Choice('Stay with them (Selina\'s request)', 'selinaintro5b', 1),
    new Choice('I want Selina to stay', 'selinaintro6', 1, 'Selina lust +1'),
    new Choice('(Kiss her)', 'selinaintrokiss', 1, 'Selina lust +1'),
    new Choice('Let\'s go somewhere private', 'selinaintro12', 1),
    new Choice('Yes', 'selinaintro12c', 1),
    new Choice('I\'ll see you there', 'e1ssex1', 1),
    // TODO: Determine if leaving Selina's panties on Taylor's bed is a required choice or not
    new Choice('Press Violet on why she won\'t', 'hottub1w', 1),
    new Choice('Compliment her', 'hottub1y', 1, 'Violet love +2'),
    new Choice('Enter naked', 'hotnaked1', 1, 'Lydia, Chelsea, Paris, Katie, Taylor, Ella lust +1'),
    new Choice('No more questions', 'hottub2e', 1, 'Just don\'t ask if there are any men at Elmwood.'),
    new Choice('Put your arm around Lydia', 'hottub2e1', 1, 'Lydia lust +1', req.choices('e1elbj1')),
    new Choice('Continue', 'hottubz2', 1, 'Faster/Slower is okay', req.choices('hottub2e1')),
    new Choice('I don\'t mind', 'hottubz4', 1, req.choices('hottubz2')),
    new Choice('Ask Lydia a cheeky question', 'e1lyjoke', 1, 'Lydia love +1', req.choices('hottub2e1')),
    new Choice('I think they sound fun', 'e1endhot2', 1, 'Chelsea, Ella, Lydia love +1'),
    new Choice('Incredible', 'e1nearend1', 1, req.choices('hottubz4')),
    new Choice('I\'ll be there', 'e1taydebrief1', 1),
    new Choice('Say goodnight to Paris', 'e1pabye', 1),
    new Choice('Ask to take her home', 'e1pabye1', 1, 'Paris love and lust +1'),
    new Choice('Say goodnight to Katie', 'e1ktbye', 1),
    new Choice('Yes', 'e1ktbye2', 1, 'Katie love +1'),
    new Choice('Say goodnight to Chelsea', 'e1chbye', 1, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella', 'Kat', 'Naomi')),
    new Choice('Then take me to bed', 'e1chbye1', 1, req.choices('e1chbye')),
    new Choice('I wish we had some time alone', 'e1chbye1a', 1, req.choices('e1chbye1', 'hottubz4')),
    new Choice('Walk home with Chelsea', 'e1leaveparty3', 1, req.choices('e1chbye1')),
    new Choice('Walk home alone', 'e1leaveparty1', 1, 'Taking Chelsea home causes problems for the twins.', (girls, { includeUnselectedForScenes }) => Girl.listIncludesNone(girls, 'Chelsea') && !isPrerequisite(girls, includeUnselectedForScenes, 'Chelsea', 'Ella') && Girl.listIncludesAny(girls, 'Ashley', 'Tasha')),
    new Choice('Compliment her', 'e1chsex2', 1, 'Chelsea love +1'),
    new Choice('Eat her pussy', 'e1chforeplay2', 1, 'Chelsea love +1'),
    // Episode 2 Choices
    new Choice('Shake her hand', 'e2sameet5x', 2, 'Saki love +1'),
    new Choice('Sure', 'e2wakeup2y', 2, 'Saki love +1'),
    new Choice('It\'s hot and exhilarating', 'ie2sameet11a', 2, 'Saki lust +1'),
    new Choice('It\'s sweet and beautiful', 'ie2sameet11b', 2, 'Saki lust +1'),
    new Choice('What videos do you make on TitsCock?', 'twinsmeet1', 2),
    new Choice('(Flirt)', 'twinsmeet1y', 2, 'Twins love and lust +1'),
    new Choice('Have you met the other flatmates?', 'twinsmeet4', 2),
    new Choice('She\'s beautiful', 'twinsmeet4a', 2, 'Saki love +1'),
    new Choice('I\'m more interested in you two', 'twinsmeet8d', 2, 'Twins love +1', req.choices('e1leaveparty3')),
    new Choice('(Reply)', 'e2lytext', 2, req.choicesOr('hottubz4', 'e1leaveparty3')),
    new Choice('I\'ll be there', 'e2lytext2', 2, req.choices('e2lytext')),
    new Choice('Sure', 'e2tashleyyoga', 2),
    new Choice('Absolutely', 'e2tashleyyoga2', 2, 'Twins lust +1'),
    new Choice('Cow', 'e2tashleyyoga2a', 2, 'Twins love +1'),
    new Choice('You\'re beautiful', 'e2twinyogacomp1', 2),
    new Choice('You\'re beautiful', 'e2twinyogacomp2', 2, 'Twins love and lust +1'),
    new Choice('(Kiss her)', 'e2lysex3', 2, req.choices('e2lytext2')),
    new Choice('Fuck Lydia', 'e2lysex4', 2, req.choices('e2lysex3')),
    new Choice('Squirting is hot!', 'e2lysexsquirt', 2, 'Required for an E4 scene', req.choices('e2lysex4')),
    new Choice('Encourage Ella to watch', 'e2lysexwatch', 2, 'Ella lust +5, required for later scene', req.choices('e2lysex4')),
    new Choice('Talk to Ella', 'e2eltalk1', 2, req.choices('e2lysexwatch')),
    new Choice('Try to make her jealous', 'e2eltalk3c', 2, 'Ella lust +1', req.choices('e2eltalk1', 'e1leaveparty3')),
    new Choice('Make her even more jealous', 'e2eltalk4a', 2, 'Ella love +2, lust +1', req.choices('e2eltalk3c')),
    new Choice('Ask her out on a date', 'e2eltalk5b', 2, req.choices('e2eltalk3c')),
    new Choice('Ask Paris out on a date', 'e2patext1', 2),
    new Choice('Don\'t text Paris', 'e2postpatext', 2, girls => Girl.listIncludesNone(girls, 'Paris') && Girl.listIncludesAny(girls, 'Ashley', 'Tasha')),
    new Choice('Flirt', 'e2patext1a', 2),
    new Choice('Thanks, Tasha', 'e2td1', 2, 'Twins love +1'),
    new Choice('Truth', 'e2tdtruth1', 2, 'Saki & Molly love +1', girls => Girl.listIncludesAny(girls, 'Saki', 'Molly') && Girl.listIncludes(girls, 'Lydia')),
    new Choice('Dare', 'e2ashneck', 2),
    new Choice('Longer, sensual kiss', 'e2ashnecklong', 2, 'Twins love and lust +1 (Requires dare)'),
    new Choice('Sure', 'e2tdsakissplayer', 2, 'Saki love +2'),
    new Choice('Truth', 'e2truth2', 2),
    // new Choice('Dare', 'e2ashspank', 2), // TODO: Uncomment later if flustering Molly is important
    new Choice('Yes (don\'t specify)', 'e2truth2a', 2, 'Saki, Molly, Twins love +1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Saki', 'e2truth2b', 2, 'Saki love +5, Molly, Twins love -1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Molly', 'e2truth2c', 2, 'Molly love +5, Saki, Twins love -1', (girls, _, { skillPlan }) => Girl.listIncludesNone(girls, 'Ashley', 'Tasha') || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Tasha & Ashley', 'e2truth2d', 2, 'Twins love +2, Saki, Molly love -2.'),
    new Choice('I dare you to flash your boobs.', 'e2tdround5', 2),
    new Choice('Turn around', 'e2tdturn', 2),
    new Choice('Dare', 'e2tdshowdickoption', 2, 'Saki love +1'),
    new Choice('Show your dick', 'e2tdshowdickoption2', 2, 'Saki, Molly, Twins lust +1'),
    new Choice('Make out with Tasha', 'e2tdround7', 2, 'Twins love +1'),
    new Choice('Defend her', 'e2tdround8', 2),
    new Choice('Sure', 'e2twinhj2', 2),
    new Choice('You can do it', 'e2twinhj4', 2),
    new Choice('You can make me even harder', 'e2twinhj7', 2),
    new Choice('(Kiss her)', 'e2sanight2', 2, 'Saki love +2'),
    new Choice('Buy Molly a vibrator', 'e2ordervibrator1', 2),
    new Choice('Buy DupliDick Vibe', 'e2ordervibrator2', 2),
    new Choice('Introduce yourself', 'e2ntalkx1', 2),
    new Choice('I\'m excited', 'e2ntalkx1b', 2, 'Naomi love +1', req.noSkill('Scholar', 'e1')),
    new Choice('I love her research', 'e2ntalkx1scholar', 2, 'Naomi love +2', req.skill('Scholar', 'e1')),
    new Choice('She\'s fantastic', 'e2ntalk2', 2, 'Naomi love +1'),
    new Choice('Highest mark in exam', 'e2nex', 2, 'Naomi love +1'),
    new Choice('Tell two truths, one lie', 'e22tl', 2, 'Naomi love +1'),
    // +20 Skill Points
    ...addSkills(2, 'e2a'),
    new Choice('Have lunch with Naomi', 'e2flecfinal', 2),
    new Choice('Talk to Dr. Riley', 'e2flotalk', 2),
    new Choice('Move seats', 'e2vlecture1', 2, (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Nina', 'Dr. Riley', 'Dr. Novotná')),
    new Choice('Answer', 'e2panswer1a', 2, 'Naomi, Dr. Novotná love +1', req.skill('Scholar', 'e2a')),
    new Choice('Stay Quiet', 'e2panswer1b', 2, req.noSkill('Scholar', 'e2a')),
    // +10 Skill Points
    ...addSkills(2, 'e2b'),
    new Choice('Talk to Dr. Novotná first', 'e2vertalk', 2),
    new Choice('I\'m interested', 'e2ninatalk2', 2),
    new Choice('Show me the lake & lighthouse', 'e2viextended', 2),
    new Choice('How have you been?', 'e2vilakechat', 2),
    new Choice('I want to be more than friends', 'e2vilove', 2, 'Violet love +5'),
    new Choice('I love Elmwood.', 'e2lighthouse1', 2, 'Violet love +1'),
    new Choice('Compliment her', 'e2eldate0', 2, 'Ella love +1', req.choices('e2eltalk5b')),
    new Choice('Ask about cheerleading', 'e2eldatemenu1', 2, req.choices('e2eltalk5b')),
    new Choice('Ask about her gymnastics', 'e2eldatemenu2', 2, req.choices('e2eltalk5b')),
    new Choice('That\'s so impressive!', 'e2eldategym', 2, 'Ella love +1', req.choices('e2eltalk5b')),
    new Choice('Ask about her friends', 'e2eldatemenu3', 2, req.choices('e2eltalk5b')),
    new Choice('Seduce her', 'e2eldateflirt', 2, req.choices('e2eltalk5b')),
    new Choice('You were better', 'e2elaftersex1', 2, 'Ella love +1', req.choices('e2eltalk5b')),
    new Choice('Meet Nina', 'e2infiltration0', 2),
    new Choice('Let\'s do this. (CONTINUE)', 'e2infiltration1', 2),
    new Choice('(Scan keycard)', 'e2infiltration2', 2),
    new Choice('Straight - through Dr. Novotná\'s lecture room', 'e2infiltration3', 2),
    new Choice('Good idea.', 'e2infiltration4', 2, 'Nina love +1'),
    new Choice('Let\'s take photos', 'e2infiltration5', 2),
    new Choice('Flirt', 'e2infiltration6', 2),
    new Choice('(Fuck her)', 'e2nisex', 2),
    // Episode 3
    new Choice('He pioneered structuralism', 'e3flec1', 3, 'Naomi love +2', req.skill('Scholar', 'e2b')),
    new Choice('He\'s dead', 'e3flec3', 3, req.noSkill('Scholar', 'e2b')),
    // +20 Skill Points
    ...addSkills(3, 'e3a'),
    new Choice('We should study together', 'e3essay2', 3),
    new Choice('(Reply)', 'e3chtext1', 3, req.choices('e1leaveparty3')),
    new Choice('Small talk', 'e3chtext2', 3, 'Chelsea love +1', req.choices('e3chtext1')),
    new Choice('Ask on date', 'e3chtext3', 3, req.choices('e3chtext1')),
    new Choice('Say hello', 'e3ctalk', 3, req.choices('joey5')),
    new Choice('Ask her what she means', 'e3ctalk2', 3, 'Chloe love +1', req.choices('joey5')),
    new Choice('Offer to give her some advice', 'e3ctalk7', 3, 'Chloe love +1', req.skillAndChoices('Dexterity', 'e3a', 'joey5')),
    new Choice('I\'ll be there', 'e3femsocattend', 3, 'Taylor, Katie love +2', (girls, { includeUnselectedForScenes }) => isPrerequisite(girls, includeUnselectedForScenes, 'Taylor', 'Katie')),
    new Choice('All of them', 'e3vlec9', 3, 'Naomi love +1', req.skill('Scholar', 'e3a')),
    // +20 Skill Points
    ...addSkills(3, 'e3b'),
    new Choice('Visit Dr. Riley', 'e3ftalk', 3),
    new Choice('Ask an intelligent question', 'e3floessayq0', 3, req.skill('Deception', 'e3b')),
    new Choice('Ask a question about the essay', 'e3floessayq1', 3),
    new Choice('Ask another question about the essay', 'e3floessayq2', 3),
    new Choice('Make small talk', 'e3flost', 3),
    new Choice('Compliment her teaching', 'e3flostx', 3),
    new Choice('She\'s ok, you\'re better', 'e3flostx2', 3, 'Dr. Riley love +1'),
    new Choice('Compliment her office', 'e3floof', 3),
    new Choice('Flirt', 'e3flofli', 3),
    new Choice('Ask about him', 'e3flofli1', 3),
    new Choice('Flirt', 'e3flofli3', 3, 'Dr. Riley love +1, lust +2', req.skill('MILF Enthusiast', 'e3b')),
    new Choice('Flirt', 'e3flofli3a', 3, 'Dr. Riley love +1, lust +2', req.skill('MILF Enjoyer', 'e3b')),
    new Choice('It was thought provoking', 'e3femsoc2c', 3, 'Taylor, Katie love +1', req.choices('e3femsocattend')),
    new Choice('You look so beautiful', 'e3kttalk1x', 3, 'Katie love +1', (girls, { includeUnselectedForScenes }, { shownChoices }) => hasChoices(shownChoices, 'e3femsocattend') && isPrerequisite(girls, includeUnselectedForScenes, 'Katie', 'Taylor')),
    new Choice('Flirt', 'e3kttalk2b', 3, 'Katie love and lust +1', req.choices('e3kttalk1x')),
    new Choice('Text me when you\'re home safe', 'e3kttalk4b', 3, req.choices('e3kttalk1x')),
    new Choice('Kiss/Hug her', 'e3ktkisshug', 3, 'Katie love +1', req.choices('e3kttalk4b')),
    new Choice('(Offer your jacket)', 'e3jacket', 3, 'Taylor love +5, Katie love +1', req.choices('e3ktkisshug')),
    new Choice('Gestalt School', 'e3nstudy1a', 3, 'Naomi love +1', req.skill('Scholar', 'e3b')),
    new Choice('(Serious)', 'e3nstudy1b', 3, req.noSkill('Scholar', 'e3b')),
    new Choice('Help her more', 'e3nstudy2', 3, 'Naomi love +1', req.skill('Persuasion', 'e3b')),
    new Choice('This one\'s great', 'e3nstudy2c', 3, 'Naomi love +2', req.skill('Deception', 'e3b')),
    new Choice('This one\'s ok', 'e3nstudy2b', 3, 'Naomi love +1', (_, __, { skillPlan }) => hasSkill('Scholar', 'e3b', skillPlan) && !hasSkill('Deception', 'e3b', skillPlan)),
    new Choice('(Reassure her & flirt)', 'e3nstudy5c', 3, 'Naomi love +1'),
    new Choice('We\'ll get through it.', 'e3nstudy7b', 3, 'Naomi love +1'),
    new Choice('Kiss her', 'e3nkiss', 3), // Has love requirement. Should be guaranteed if on path
    new Choice('No', 'e3nkissx', 3, 'Naomi love +1'),
    new Choice('Message Selina', 'e3stext', 3),
    new Choice('I don\'t want a date', 'e3stext1', 3),
    new Choice('That\'s not me', 'e3stalk', 3),
    new Choice('Casual sex', 'e3stalk2c', 3),
    new Choice('I promise', 'e3stalk3', 3),
    new Choice('(Flirt)', 'e3stalk4a', 3),
    new Choice('Fuck even harder', 'e3stalk5', 3, 'Selina lust +1'),
    new Choice('Fuck her', 'e3ssex', 3),
    new Choice('Organise date', 'e3patextdate1', 3),
    new Choice('Flirt', 'e3saki3c', 3, 'Saki love +1'),
    new Choice('Kiss her', 'e3saki4', 3),
    new Choice('What\'s the banana for?', 'e3sakibanana', 3),
    new Choice('I can teach you', 'e3sakibanana1', 3),
    new Choice('You did amazing', 'e3sakibanana1a', 3, 'Saki love +1'),
    new Choice('Corrupt', 'e3sakicorruption', 3, 'Saki love +2', req.skill('Corruption', 'e3b')),
    new Choice('Yes', 'e3gym1', 3),
    new Choice('Looks hot', 'e3gym2', 3, 'Twins love and lust +1'),
    new Choice('Easily', 'e3gym3', 3, 'Twins love +1', req.skill('Ripped', 'e3b')),
    new Choice('100kg', 'e3gym3b', 3, 'Twins love +1', (_, __, { skillPlan }) => hasSkill('Ripped', 'e3b', skillPlan) && !hasSkill('Warrior', 'e3b', skillPlan)),
    new Choice('160kg', 'e3gym3c', 3, 'Twins love +2', req.skill('Warrior', 'e3b')),
    new Choice('Flirt', 'e3gym5', 3, req.skill('Ripped', 'e3b')),
    new Choice('Flirt', 'e3gym6', 3, req.skill('Ripped', 'e3b')),
    new Choice('Sure', 'e3gym7', 3, req.skill('Ripped', 'e3b')),
    new Choice('Flirt', 'e3gym10', 3, req.skill('Ripped', 'e3b')),
    new Choice('Hold', 'e3gym11', 3, req.skill('Ripped', 'e3b')),
    new Choice('HOLD!', 'e3gym12', 3, 'Twins love +1', req.skill('Ripped', 'e3b')),
    new Choice('HOOOLDDDD!', 'e3gym13', 3, req.skill('Ripped', 'e3b')),
    new Choice('HOOOOOOOOOOLDDDD!', 'e3gym14', 3, req.skill('Warrior', 'e3b')),
    new Choice('HOOOOOOOOOOLDDDD!', 'e3gym15', 3, 'Twins love +2', req.skill('Warrior', 'e3b')),
    new Choice('Seeing a friend (lie about date)', 'e3massage1a', 3, (girls, _, { skillPlan }) => Girl.listIncludes(girls, 'Paris') && hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Nothing (lie about Paris)', 'e3massage1b', 3, (girls, _, { skillPlan }) => Girl.listIncludes(girls, 'Paris') && !hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Not much, seeing a friend', 'e3massage1c', 3, girls => Girl.listIncludesNone(girls, 'Paris')),
    new Choice('Nothing much', 'e3massage1d', 3, girls => Girl.listIncludesNone(girls, 'Paris')),
    new Choice('Flirt with both', 'e3massage2c', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Try to kiss them', 'e3tashleykiss', 3, 'Twins love +1', (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Offer to massage them', 'e3massage3', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Massage their asses', 'e3massage4', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Massage their pussies', 'e3massage5', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Take off their panties', 'e3massage6', 3, (girls, _, { skillPlan }) => (Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)),
    new Choice('Make them both cum', 'e3massagedx', 3, (girls, _, { skillPlan }) => ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan)) && hasSkill('Oral Mastery', 'e3b', skillPlan)),
    new Choice('Compliment her', 'e3padate1a', 3, 'Paris love +1'),
    new Choice('Roast her outfit', 'e3padate1c', 3, 'Paris love +1'),
    new Choice('Give Paris a striptease', 'e3padate3', 3, 'Paris love +1'),
    new Choice('Tease her', 'e3padate4b', 3, 'Paris love +1'),
    new Choice('Kiss her', 'e3padate6a', 3, 'Paris love +2'),
    new Choice('Come back to mine?', 'e3padate8', 3),
    new Choice('She\'s just a friend', 'e3confront2', 3, (girls, _, { skillPlan }) => Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && hasSkill('Deception', 'e3b', skillPlan) && ((Girl.listIncludesAny(girls, 'Ashley', 'Tasha') && !hasSkill('Ripped', 'e3b', skillPlan)) || hasSkill('Ripped', 'e3b', skillPlan))),
    new Choice('Here\'s your water', 'e3padate10', 3),
    new Choice('Kiss Paris', 'e3padate10a', 3),
    new Choice('Go further', 'e3padate12', 3),
    new Choice('Confirm plans', 'e3satwake3', 3, req.choices('e3chtext3')),
    new Choice('Compliment Chelsea', 'e3ddate5', 3, 'Chelsea love +1'),
    new Choice('You should stay', 'e3ddate7', 3, (girls, { includeSideGirls }) => includeSideGirls || Girl.listIncludes(girls, 'Kat')),
    new Choice('You should go', 'e3ddatekatleaves', 3, 'Chelsea love -2', (girls, { includeSideGirls }) => !includeSideGirls && Girl.listIncludesNone(girls, 'Kat')),
    new Choice('COCKS OUT, LADS!', 'e3ddate8', 3, 'Chelsea love +2, Kat lust +1', req.choices('e3ddate7')),
    new Choice('Make out with Chelsea', 'e3ddate9', 3, 'Chelsea love +1', req.choices('e3ddate7')),
    new Choice('Flirty', 'e3ddate10a', 3, 'Kat lust +1', req.choices('e3ddate7')),
    new Choice('Flirty', 'e3ddate11a', 3, 'Kat lust +1', req.choices('e3ddate7')),
    new Choice('A kiss', 'e3ddate90', 3, req.choices('e3ddate7')),
    new Choice('Help Chelsea seduce Kat', 'e3ddate110', 3, req.choices('e3ddate7')),
    // Episode 4
    new Choice('Sure', 'e4flec3', 4),
    // +20 Skill Points
    ...addSkills(4, 'e4a'),
    new Choice('Sure', 'e4flec8', 4, req.choices('e3essay2')),
    // TODO: Add telling Chelsea to either tell Lydia about the threesome or not here, once outcomes are known
    // +10 Skill Points
    ...addSkills(4, 'e4b'),
    new Choice('Ask her out on a date', 'e4ninaday2a', 4),
    new Choice('Teacher\'s lounge', 'e4ninaday2axa', 4),
    new Choice('Visit Tasha & Ashley', 'e4montash', 4),
    new Choice('Lie', 'e4montash1', 4, req.choices('e3ddate110')),
    new Choice('Watch film', 'e4montash4', 4),
    new Choice('No (kiss her)', 'e4montash5', 4),
    new Choice('Make an excuse', 'e4ninanight', 4, girls => Girl.listIncludes(girls, 'Nina')),
    new Choice('Sleep with them', 'e4montash6', 4, girls => Girl.listIncludesNone(girls, 'Nina')),
    new Choice('You look beautiful', 'e4infil6', 4, 'Nina love +1'),
    new Choice('Ukraine', 'e4flagua', 4, 'Nina love +1 (If all flags correct)'),
    new Choice('Argentina', 'e4flagar', 4),
    new Choice('U.S.A.', 'e4flagus', 4),
    new Choice('Belgium', 'e4flagbe', 4),
    new Choice('India', 'e4flagin', 4),
    new Choice('South Africa', 'e4flagza', 4),
    new Choice('Czech Republic', 'e4flagcz', 4),
    new Choice('Italy', 'e4flagit', 4),
    new Choice('France', 'e4flagfr', 4),
    new Choice('Canada', 'e4flagca', 4),
    new Choice('Switzerland', 'e4flagch', 4),
    new Choice('Spain', 'e4flages', 4),
    new Choice('Brazil', 'e4flagbr', 4),
    new Choice('China', 'e4flagcn', 4),
    new Choice('Australia', 'e4flagau', 4),
    new Choice('Put your arm around her', 'e4niseduce', 4),
    new Choice('I want to fuck you', 'e4nisex', 4),
    new Choice('Invite her in', 'e4tay2', 4, req.choices('e3jacket')),
    new Choice('Compliment her outfit', 'e4tay3', 4, 'Taylor love +1', req.choices('e3jacket')),
    new Choice('Ask her about Katie', 'e4tay3a', 4, 'Katie love +1', (girls, _, { shownChoices }) => Girl.listIncludes(girls, 'Katie') && hasChoices(shownChoices, 'e3jacket')),
    new Choice('Ask her about Violet', 'e4tay3b', 4, req.skillAndChoices('Lie Detection', 'e4b', 'e3jacket')),
    new Choice('Tell her about the Gorillas', 'e4tay3c', 4, 'Taylor love +1', (girls, _, { shownChoices }) => Girl.listIncludes(girls, 'Katie') && hasChoices(shownChoices, 'e3jacket')),
    new Choice('Flirt', 'e4tay5', 4, 'Taylor love +1', (girls, _, { shownChoices }) => Girl.listIncludes(girls, 'Katie') && hasChoices(shownChoices, 'e3jacket')),
    new Choice('Help control confounding variables', 'e4naomi11b', 4, 'Naomi love +1', req.choices('e4flec8')),
    new Choice('No effect', 'e4naomi1d', 4, 'Naomi love +1', req.skillAndChoices('Persuasion', 'e4b', 'e4naomi11b')),
    new Choice('Test her further', 'e4naomi2b', 4, 'Naomi love +1', req.skillAndChoices('Deception', 'e4b', 'e4flec8')),
    new Choice('Make a romantic bet', 'e4naomi4a', 4, req.choices('e3nkiss', 'e4flec8')),
    new Choice('Flirt', 'e4naomi5a', 4, req.choices('e3nkiss', 'e4flec8')),
    new Choice('Kiss her', 'e4naomi6', 4, req.choices('e4naomi5a')),
    new Choice('Tell her about your experiences', 'e4naomi7', 4, (_, __, { shownChoices }) => hasChoices(shownChoices, 'e4naomi6') && hasChoicesOr(shownChoices, 'e1leaveparty3', 'e3padate12')),
    new Choice('Tell her about Paris', 'e4naomipa', 4, 'Naomi lust +1', req.choices('e4naomi7', 'e3padate12')),
    new Choice('Tell her about Selina', 'e4naomis', 4, 'Naomi lust +1', req.choices('e4naomi7', 'e1ssex1')),
    new Choice('Tell her about Lydia', 'e4naomily', 4, 'Naomi lust +1', req.choices('e4naomi7', 'e2lysex4')),
    new Choice('Tell her about Ella', 'e4naomiel', 4, 'Naomi lust +1', req.choices('e4naomi7', 'e2elaftersex1')),
    new Choice('Tell her about Chelsea', 'e4naomich', 4, 'Naomi lust +1', req.choices('e4naomi7', 'e1leaveparty3')),
    // TODO: Add "Help Naomi"/"Sabotage Naomi" choices if determined to be important in the future
    new Choice('Text Selina', 'e4selina2', 4, req.choices('e3stalk3')),
    new Choice('Put her in her place', 'e4dd2', 4, req.skill('Persuasion', 'e4b')),
    new Choice('Text Violet', 'e4vitext', 4),
    new Choice('I\'m free', 'e4ctext', 4, req.choices('e3ctalk7')),
    new Choice('Text Paris', 'e4patext1', 4, req.choices('e3padate12')),
    new Choice('Nominate yourself for course rep', 'e4cereal2', 4),
    new Choice('I\'m highly empathetic & communicative', 'e4vnom1b', 4, req.skill('Persuasion', 'e4b')),
    new Choice('I have lots of friends on the course', 'e4vnom1c', 4, req.noSkill('Persuasion', 'e4b')),
    new Choice('I\'ll always try my best', 'e4vnom1d', 4, req.noSkill('Persuasion', 'e4b')),
    new Choice('We like it', 'e4vnom2b', 4),
    new Choice('Many struggle with the strict environment', 'e4vnom3e', 4, req.skill('Persuasion', 'e4b')),
    new Choice('We don\'t like it', 'e4vnom3c', 4, req.noSkill('Persuasion', 'e4b')),
    new Choice('Flirt', 'e4vnom4a', 4, 'Dr. Novotná love +3', (_, __, { skillPlan }) => hasSkill('Scholar', 'e4b', skillPlan) && !hasSkill('Persuasion', 'e4b', skillPlan) && hasSkill('MILF Expert', 'e4b', skillPlan)),
    new Choice('Flirt', 'e4vnom4b', 4, 'Dr. Novotná love +9', (_, __, { skillPlan }) => hasSkill('Persuasion', 'e4b', skillPlan) && hasSkill('MILF Expert', 'e4b', skillPlan)),
    new Choice('Buy Florence flowers', 'e4floflowers2', 4, 'Dr. Riley love +4', req.choices('e3flofli3a')),
    new Choice('Text Katie', 'e4kttext', 4),
    // TODO: Check if HW tournament offers any love in the future
    new Choice('Sign me up!', 'e4vi2', 4),
    new Choice('Flirt', 'e4vi2a', 4, 'Violet love +4, lust +1'),
    new Choice('It looks cool!', 'e4vi4', 4, 'Violet love +1'),
    new Choice('Steal her controller (Flirt)', 'e4vi7', 4),
    new Choice('Kiss her', 'e4vikiss', 4),
    new Choice('Offer to cook her dinner', 'e4cook2', 4),
    new Choice('Ask Jordan about what Saki said', 'e4joey2saki', 4, req.choices('e4ctext')),
    new Choice('Ask about their degrees', 'e4joey3a', 4, req.choices('e4ctext')),
    new Choice('Ask about their hobbies', 'e4joey3b', 4, req.choices('e4ctext')),
    new Choice('Compliment their outfits', 'e4joey3c', 4, req.choices('e4ctext')),
    new Choice('Let\'s play pool (Continue)', 'e4joey4', 4, req.choices('e4ctext')),
    new Choice('Talk about her cookies', 'e4ktcall1a', 4, 'Katie love +1', req.choices('e3jacket')),
    new Choice('Talk about seeing Violet', 'e4ktcall1b', 4, 'Katie love +1', req.choices('e4vitext')),
    new Choice('You should keep your promise', 'e4ktcall1bvi', 4, 'Katie, Taylor, Violet love +1', req.choices('e4ktcall1b', 'e4vikiss')),
    new Choice('Ask her out on a date', 'e4ktcall1c', 4),
    new Choice('Praise her', 'e4saki1', 4, 'Saki love +1'),
    new Choice('Flirt', 'e4saki3', 4, 'Saki love +1'),
    new Choice('Kiss her', 'e4saki4', 4, 'Saki lust +1'),
    new Choice('Go further & corrupt her', 'e4sacorrupt', 4, req.skill('Corruption', 'e4b')),
    new Choice('Go further', 'e4safinger', 4, req.noSkill('Corruption', 'e4b')),
    new Choice('Teach her that you own her orgasms', 'e4saownership', 4, (_, __, { skillPlan }) => hasSkill('Ownership', 'e4b', skillPlan) && hasSkill('Dexterity', 'e4b', skillPlan)),
    new Choice('Make her cum', 'e4sacumx', 4, (_, __, { skillPlan }) => !hasSkill('Ownership', 'e4b', skillPlan) && hasSkill('Dexterity', 'e4b', skillPlan)),
    new Choice('(Go with Lydia and Ella)', 'e4bjcomp2', 4, req.choices('e1elbj1')),
    new Choice('Threaten him', 'e4halloleave1a', 4, 'Twins love +1'),
    new Choice('Punch him', 'e4halloleave1b', 4, 'Twins love +10, lust +2', req.skill('Warrior', 'e4b')),
    new Choice('I want the cuddles', 'e4witchdecision', 4, req.choicesOr('e3padate8', 'e1leaveparty3')),
    new Choice('Fuck yes!', 'e4pole1', 4, req.choices('e4bjcomp2', 'e2lysexsquirt')),
    new Choice('Talk to Ella', 'e4ellatalk', 4, req.choices('e4pole1', 'e2elaftersex1')),
    new Choice('It\'s ok if you can\'t squirt', 'e4ellatalk1b', 4, req.choices('e4ellatalk')),
    new Choice('No, I don\'t care', 'e4ellatalk1bx', 4, req.choices('e4ellatalk1b')),
    new Choice('Compliment here', 'e4ellatalk1d', 4, req.choices('e4ellatalk')),
    new Choice('(Continue)', 'e4ellatalk2', 4, req.choices('e4ellatalk')),
    new Choice('Something relaxed', 'e4ellatalk3', 4, req.choices('e4ellatalk2')),
    new Choice('Compliment her', 'e4eldate', 4, req.choices('e4ellatalk3')),
    new Choice('Fuck Ella', 'e4elsex', 4, req.choices('e4ellatalk3')),
    new Choice('Cuddle Lydia', 'e4postelsex1', 4, req.choices('e4elsex')), // TODO: Check if this is required for any future Lydia content and add a `includeUnselectedForScenes` check
    // Episode 5
    ...addSkills(5, 'e5a'),
    new Choice('Make sure everyone has a voice', 'e5vlec2a', 5, (girls, __, { shownChoices, skillPlan }) => hasChoices(shownChoices, 'e4cereal2') && hasSkill('Persuasion', 'e5a', skillPlan) || (hasSkill('Scholar', 'e5a', skillPlan) && Girl.listIncludes(girls, 'Naomi'))),
    ...addSkills(5, 'e5b'),
    new Choice('(Flirt)', 'e5ntalk1', 5, req.choices('e3nkiss')),
    new Choice('Hear him out', 'e5ethan1', 5),
    new Choice('Yes, I\'m interested', 'e5ethan4', 5),
    new Choice('Warn Taylor', 'e5taytext', 5),
    new Choice('(Cuddle her)', 'e5saki3', 5, req.choices('e3sakibanana1')),
    new Choice('Kiss her', 'e5saki3a', 5, req.choices('e3sakibanana1')),
    new Choice('Go further', 'e5saki4a', 5, 'Saki lust +1', (_, __, { shownChoices, skillPlan }) => hasChoices(shownChoices, 'e3sakibanana1') && !hasSkill('Corruption', 'e5b', skillPlan)),
    new Choice('Go further & corrupt her', 'e5saki4b', 5, 'Saki lust +1', req.skillAndChoices('Corruption', 'e5b', 'e3sakibanana1')),
    new Choice('Extra training', 'e5sakiobedience', 5, 'The order of the commands don\'t matter, as long as you do at least 6', req.choices('e5saki4b')),
    new Choice('(Continue)', 'e5sakiobedience2', 5, req.choices('e5sakiobedience')),
    new Choice('Give her permission', 'e5sakiobedience3a', 5, req.skillAndChoices('Ownership', 'e5b', 'e5sakiobedience2')),
    new Choice('Don\'t let her cum', 'e5sakiobedience3b', 5, req.skillAndChoices('Ownership', 'e5b', 'e5sakiobedience2')),
    new Choice('Let\'s do it', 'e5vitext1', 5, req.choices('e4vikiss')),
    new Choice('Ask her out', 'e5taycoffee3', 5, req.choices('e5taytext')),
    new Choice('I\'ll be there', 'e5selinatext', 5, girls => !Girl.listIncludesAny(girls, 'Ashley', 'Tasha')),
    new Choice('I\'m busy', 'e5selinatext1', 5, 'Seeing Selina here ends the path with the Twins', girls => Girl.listIncludesAny(girls, 'Ashley', 'Tasha')),
    new Choice('Suck on her nipple', 'e5selina1a', 5, 'Selina lust +1', req.choices('e5selinatext')),
    new Choice('Earthquake', 'e5selinaquake', 5, req.skillAndChoices('Earthquake', 'e5b', 'e5selinatext')),
    new Choice('I\'m free', 'e5ctext1', 5, req.choices('e4joey4')),
    new Choice('Apologise and we have a deal', 'e5molly1b', 5, req.choices('e4cook2')),
    new Choice('Help her wash up', 'e5cook4a', 5, 'Molly love +1', req.choices('e5molly1b')),
    // TODO: add exam answers to Naomi/Florence/Veronika as needed
    new Choice('C', 'e5exam1c', 5, req.noChoices('e2infiltration1')),
    new Choice('C', 'e5exam2', 5, req.choices('e5exam1c')),
    new Choice('FALSE', 'e5exam3', 5, req.choices('e5exam1c')),
    new Choice('TRUE', 'e5exam4', 5, req.choices('e5exam1c')),
    new Choice('A', 'e5exam5', 5, req.choices('e5exam1c')),
    new Choice('D', 'e5exam6', 5, req.choices('e5exam1c')),
    new Choice('Hang out with Naomi', 'e5naomiplay', 5, req.choices('e3nkiss')),
    new Choice('Go further', 'e5naomiplay1', 5, 'Naomi lust +1', req.choices('e5naomiplay')),
    new Choice('I\'ve had better', 'e5naomicuck', 5, 'Naomi lust +3', req.choicesOr('e4naomis', 'e4naomily', 'e4naomiel', 'e4naomich')),
    new Choice('Yours is great', 'e5naomiplaynocuck', 5, req.noChoices('e5naomicuck')),
    new Choice('Lay back, (Selina/Lydia/Ella/Chelsea)', 'e5naomicuck2', 5, 'Naomi lust +2', req.choices('e5naomicuck')),
    new Choice('Finger her', 'e5naomicuckfinger', 5, req.choices('e5naomicuck2')),
    new Choice('Text Paris', 'e5patext1', 5, req.choices('e4patext1')),
    new Choice('Your relationship with Atkins', 'e5floffice1a', 5, req.choices('e5vlec2a')),
    new Choice('Flirt', 'e5floffice1x', 5, req.skillAndChoices('MILF Enthusiast', 'e5b', 'e5floffice1a')),
    new Choice('Make conversation', 'e5floffice2a', 5, req.choices('e5vlec2a')),
    new Choice('Flirt', 'e5floffice2x', 5, 'Dr. Riley love +1', req.skillAndChoices('MILF Enjoyer', 'e5b', 'e5floffice2a')),
    new Choice('Visit Tasha & Ashley', 'e5tashleytalk', 5),
    new Choice('Ashley red, Tasha blue', 'e5tashleytalk1x', 5),
    new Choice('You\'re lying', 'e5tashleytalk2', 5),
    new Choice('Ask them out on a date', 'e5tashleytalk2y', 5, (girls, _, { shownChoices }) => (Girl.listIncludesNone(girls, 'Chelsea', 'Paris') && hasChoices(shownChoices, 'e4halloleave1b')) || hasChoices(shownChoices, 'e4witchdecision')),
    // TODO: HW tournament sign up here if important
    new Choice('Let\'s go.', 'e5viflat10', 5, req.choices('e4vi2')),
    new Choice('Be defensive', 'e5tournament1a', 5, 'Violet love +2', req.choices('e5viflat10')),
    new Choice('(Continue)', 'e5joeydrinks', 5, 'Just do not flirt', req.choices('e5ctext1')),
    new Choice('Come back to mine?', 'e5papresex1', 5, 'Paris lust +3', req.choices('e5patext1')),
    new Choice('Finger her', 'e5pafingerslow', 5, 'Paris lust +1', req.choices('e5papresex1')),
    new Choice('Earthquake', 'e5parisquake', 5, req.skillAndChoices('Earthquake', 'e5b', 'e5papresex1')),
    new Choice('I\'ll do it', 'e5joskate4', 5, req.choices('e5joeydrinks')),
    new Choice('Call Vivian', 'e5vivcall1', 5),
    new Choice('About Time', 'e5ktpicnic2', 5, 'Katie love +2', req.choices('e4ktcall1c')),
    new Choice('Loving & loyal', 'e5ktpicnic3b', 5, req.choices('e4ktcall1c')),
    new Choice('Baking skills', 'e5ktpicnic3d', 5, req.choices('e4ktcall1c')),
    new Choice('Kiss her', 'e5ktpicnic6', 5, req.choices('e4ktcall1c')),
    new Choice('Stay over', 'e5ktpicnic7', 5, 'Katie love +1', req.choices('e4ktcall1c')),
    new Choice('Skinny caramel latte', 'e5ashleydate2', 5, 'Twins love +1', req.choices('e5tashleytalk2y')),
    new Choice('I\'ll train both of you', 'e5vivian2', 5, (_, __, { skillPlan }) => hasSkill('Corruption', 'e5b', skillPlan) && hasSkill('MILF Enjoyer', 'e5b', skillPlan)),
    new Choice('I\'ll train Trixie', 'e5vivian9', 5, req.noChoices('e5vivian2')),
    new Choice('Make conversation', 'e5flooffice2', 5, req.choices('e5vlec2a')),
    new Choice('Ask about her Research', 'e5flooffice2a', 5, req.choices('e5flooffice2')),
    new Choice('A study over a long period of time', 'e5flooffice2x', 5, 'Dr. Riley love +1', req.skillAndChoices('Deception', 'e5b', 'e5flooffice2')),
    new Choice('Flirt', 'e5flooffice4', 5, 'Dr. Riley love +2', req.skillAndChoices('MILF Enjoyer', 'e5b', 'e5flooffice2')),
    new Choice('Be direct and blunt', 'e5veronikaoffice1b', 5, req.choices('e5vlec2a')),
    new Choice('Put her in her place', 'e5veronikaoffice2', 5, req.skillAndChoices('Corruption', 'e5b', 'e5vlec2a')),
    new Choice('Agree with her', 'e5veronikaoffice2x', 5, (_, __, { shownChoices, skillPlan }) => hasChoices(shownChoices, 'e5vlec2a') && !hasSkill('Corruption', 'e5b', skillPlan)),
    new Choice('We need 10 minutes', 'e5veronikaoffice3b', 5, req.choices('e5veronikaoffice2')),
    new Choice('We need 15 minutes', 'e5veronikaoffice3c', 5, (_, __, { shownChoices, skillPlan }) => hasChoices(shownChoices, 'e5veronikaoffice2') && hasSkill('Ownership', 'e5b', skillPlan) && hasSkill('Dexterity', 'e5b', skillPlan)),
    new Choice('...beautiful', 'e5taydate2', 5, 'Taylor love +1', req.choices('e5taycoffee3')),
    new Choice('Ask about Selina', 'e5taydate4c', 5, 'Reveals Taylor\'s perk briefly', req.choices('e5taydate2')),
    new Choice('Kiss her', 'e5taydate8', 5, req.choices('e5taydate2')),
]

export const selectChoice = (id: string): Choice => {
    const choice = choices.find(c => c.optionId === id)
    if (!choice) {
        throw new Error(`Choice ${id} does not exist`)
    }
    return choice
}

export const conflictingChoices: Choice[][] = [
    ['cheerkiss0', 'cheerkisslyd', 'cheerkissch', 'cheerkissel'].map(id => selectChoice(id)),
    ['preselinaintrox1', 'preselinaintrox3', 'preselinaintrox4'].map(id => selectChoice(id)),
    ['ie2sameet11a', 'ie2sameet11b'].map(id => selectChoice(id)),
    ['e2tdtruth1', 'e2ashneck'].map(id => selectChoice(id)),
    // ['e2truth2', 'e2ashspank'].map(id => selectChoice(id)),
    ['e2truth2a', 'e2truth2b', 'e2truth2c', 'e2truth2d'].map(id => selectChoice(id)),
    ['e2ntalkx1b', 'e2ntalkx1scholar'].map(id => selectChoice(id)),
    ['e3massage1a', 'e3massage1b', 'e3massage1c', 'e3massage1d'].map(id => selectChoice(id)),
    ['e3padate1a', 'e3padate1c'].map(id => selectChoice(id)),
    ['e4vnom1c', 'e4vnom1d'].map(id => selectChoice(id)),
    ['e5sakiobedience3a', 'e5sakiobedience3b'].map(id => selectChoice(id)),
    ['e5ktpicnic3b', 'e5ktpicnic3d'].map(id => selectChoice(id)),
]
