import { Girl } from '@/elmwood/elmwood.ts'
import { selectChoice } from '@/elmwood/choices.ts'

export const chelsea = new Girl('Chelsea', 'Chelsea Porter', 'chelsea')

chelsea.addChoices(
    ...[
        'cheertalk3',
        'cheertalk4x',
        'cheertalk6x',
        'cheertalk7all',
        'cheertalk8n',
        'cheerkissch',
        'chelbj4',
        'e1chbjcum',
        'lydbj3',
        'e1elbj1',
        'hotnaked1',
        'hottub2e',
        'e1endhot2',
        'e1chbye',
        'e1chbye1',
        'e1chbye1a',
        'e1leaveparty3',
        'e1chforeplay2',
        'e2lytext',
        'e2lytext2',
        'e2lysex3',
        'e2lysex4',
        'e2lysexsquirt',
        'e3chtext1',
        'e3chtext2',
        'e3chtext3',
        'e3satwake3',
        'e3ddate5',
        'e3ddate7',
        'e3ddatekatleaves',
        'e3ddate8',
        'e3ddate9',
        'e3ddate10a',
        'e3ddate11a',
        'e3ddate90',
        'e3ddate110',
    ].map(id => selectChoice(id)),
)
